// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"CommonEventOnAttacked","status":true,"description":"攻撃を受けた際にコモンイベントを実行できるようにするプラグインです。","parameters":{}},
{"name":"AppliedElementFlag","status":true,"description":"敵が弱点を探ってくる機能を実装する補助プラグインです。","parameters":{"PrimalElement1":"1","PrimalElement2":"2","PrimalElement3":"3","PrimalElement4":"4","PrimalElement5":"5","PrimalElement6":"6","DeconstructMap1":"7,1,2","DeconstructMap2":"8,1,3","DeconstructMap3":"9,1,4","DeconstructMap4":"10,1,5","DeconstructMap5":"11,1,6","DeconstructMap6":"12,2,3","DeconstructMap7":"13,2,4","DeconstructMap8":"14,2,5","DeconstructMap9":"15,2,6","DeconstructMap10":"16,3,4","DeconstructMap11":"17,3,5","DeconstructMap12":"18,3,6","DeconstructMap13":"19,4,5","DeconstructMap14":"20,4,6","DeconstructMap15":"21,5,6"}},
{"name":"YEP_BaseTroopEvents","status":true,"description":"全ての敵グループに対して、\r\n毎回戦闘で発生するイベントを設定します。","parameters":{"Base Troop ID":"1"}},
{"name":"YEP_BattleAICore","status":true,"description":"バトルAIを、より管理されたものにすることができます。","parameters":{"Dynamic Actions":"true","Element Testing":"false","Default AI Level":"100"}}
];
